name       : flex
version    : 2.63
release    : 9
source     :
    - https://github.com/westes/flex/releases/download/v2.6.3/flex-2.6.3.tar.gz : 68b2742233e747c462f781462a2a1e299dc6207401dac8f0bbb316f48565c2aa
homepage   : http://flex.sourceforge.net
license    :
    - BSD-2-Clause
summary    : flex (fast lexical analyzer)
component  : system.devel
devel      : yes
emul32     : yes
description: |
    Flex is a tool for generating scanners (tokenizers) which are programs to recognize lexical patterns in text. It takes input files and forms pairs of regular expressions and C code, called rules. It analyzes its input for text matching the regular expressions and executes the C code on a match.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
