name        : flex
version     : 2.5.37
release     : 8
source      :
    - http://prdownloads.sourceforge.net/flex/flex-2.5.37.tar.gz : bf693433a3effe6b1f42e44abd787491e4e213984b1859545b92267a86088dd3
homepage    : http://flex.sourceforge.net
license     :
    - BSD
summary     : flex (fast lexical analyzer)
devel       : yes
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    Flex is a tool for generating scanners (tokenizers) which are programs to recognize lexical patterns in text. It takes input files and forms pairs of regular expressions and C code, called rules. It analyzes its input for text matching the regular expressions and executes the C code on a match.
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        mkdir 32 && pushd 32
    else
        mkdir 64 && pushd 64
    fi
    ../configure $CONFOPTS
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        pushd 32
    else
        pushd 64
    fi
    %make
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        pushd 32
    else
        pushd 64
    fi
    %make_install
